name: Docker Image CI for GHCR

on:
    push

jobs:
    build_and_publish:
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v3
            - name: Build and push the image
              uses: docker/login-action@v3
              with:
                  username: ${{secrets.USERNAME_K}}
                  password: ${{secrets.KRISHNA}}
              # run: |
              #   docker build -t ghcr.io/krishna1priya/arithmetic-service:latest --file Dockerfile .  
              #   docker push ghcr.io/krishna1priya/arithmetic-service:latest 
